name:                data-fetcher-hs
version:             0.1.0.0
github:              "githubuser/data-fetcher-hs"
license:             GPL
author:              "Jared Loomis"
maintainer:          "jaredloomis@protonmail.com"
copyright:           "2020 Jared Loomis"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/jaredloomis/data-fetcher-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text >=1.2.3.0 && <1.3
  - bytestring #>= 0.11.0.0
  - http-client
  - http-client-tls
  - either >= 5
  - aeson >=1.4.1.0 && <1.6
  - servant >= 0.16
  - servant-client >= 0.16
  - time
  - unordered-containers
  - vector
  - trifecta
  - cassava
  - containers

executables:
  data-fetcher-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-fetcher-hs
    - text
    - optparse-applicative
    - aeson
    - containers
    - vector
    - bytestring
    - split
    - time

tests:
  data-fetcher-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-fetcher-hs
